import { Context, APIGatewayEvent } from 'aws-lambda';
import dynamoDb from '../../../../libs/dynamodb-lib.js';
import { success, failure, error } from '../../../../libs/response-lib.js';
import { Student } from '../model/student';
import * as uuid from 'uuid';
import { cognitoAction } from '../../../../libs/cognito';
import utils from '../../../../libs/util.js';


export async function fetchStudentBasedOnEmail(email: string) {
  let params = {
    TableName: 'students',
    IndexName: 'email-index',
    KeyConditionExpression: 'email = :email',
    ExpressionAttributeValues: {
      ':email': email
    }
  };
  try {
    const result = await dynamoDb.query(params);
    return result.Items;
  }
  catch (e) {
    console.log("fetchStudentBasedOnEmail -> e", e);
    return { message: 'student not found' };
  }
}

async function updateUserInDatabase(userInfo) {
  // update user into database
  const params = {
    TableName: "students",
    Key: {
      studentId: userInfo.studentId
    },
    UpdateExpression: "SET studentName = :studentName, studentFamilyName = :studentFamilyName, memo = :memo, updatedDate = :updatedDate",
    ExpressionAttributeValues: {
      ":studentName": userInfo.studentName,
      ":studentFamilyName": userInfo.studentFamilyName,
      ":memo": userInfo.memo,
      ":updatedDate": userInfo.updatedDate,
    },
  };
  try {
    await dynamoDb.update(params);
  } catch (e) {
    console.log("updateUserInDatabase -> e", e);
  }
}

//# Method for create student in student table
export async function createStudent(_: APIGatewayEvent, adminId, body: Student, type = 1) {
  let isEmailAutoGenerated = true;
  let email = "";
  if (body.email !== "") {
    email = body.email;
    isEmailAutoGenerated = false;
  } else {
    email = `${await utils.getUniqueId()}@smartclass.jp`;
  }
  // first check same email already exist 
  let students: [Student] = await fetchStudentBasedOnEmail(email);
  console.log("🚀 ~ file: login.ts ~ line 61 ~ createStudent ~ students", students);
  let studentId = students.length > 0 ? students[0].studentId : uuid.v1()
  let enterpriseId = body.enterpriseId;
  let stduentCreationDate = students.length > 0 ? students[0].createdDate : new Date().toISOString();
  let password: string = students && students.length > 0 ? students[0].password : ('X' + uuid.v1());
  const params = {
    TableName: 'students',
    Item: {
      studentId,
      adminId,
      enterpriseId,
      studentName: body.studentName,
      studentFamilyName: body.studentFamilyName,
      password: password,
      email: email,
      createdDate: stduentCreationDate,
      updatedDate: new Date().toISOString(),
      deletedDate: null,
      lastLoginDate: new Date().toISOString(),
      memo: body.memo
    },
  };
  try {
    if (students.length > 0) {
      // update student
      await updateUserInDatabase(params.Item)
      if (isEmailAutoGenerated) params.Item.email = "";
      if (type == 1) return success(params.Item);
      else return (params.Item)
    }
    else if (!students.length) {
       // create new student in DB and Cognito
   
      const promise = new Promise(async (resolve, reject) => {
        
        //First Register in cognito
        let cUsrInfo = {
          email: email,
          password: password
        }
        await cognitoAction(1, cUsrInfo, 'register', async (data) => {
          if (data === null) {
            // register student in database
            await dynamoDb.put(params);
            resolve(data);
          }
          else if (data !== null) {
            reject(data);
          }
        });
      });
      let data = await promise;
      console.log("createStudent -> data", data);
      if (isEmailAutoGenerated) params.Item.email = "";
      if (type == 1) return success(params.Item);
      else return (params.Item)
    }
    else {
      // something goes wrong
      if (type == 1) return failure({ status: false });
      else return ({ status: false });
    }
  } catch (error) {
     // something goes wrong
    console.log('error', error);
    if (type == 1) return failure({ status: false, error: error });
    else return ({ status: false, error: error });
  }
}

export async function main(event: APIGatewayEvent, _: Context) {
  let statusCode = 0;
  try {
    const body = event.body ? JSON.parse(event.body) : {};
    console.log("main -> body", body)
    const adminId = event.requestContext.identity.cognitoIdentityId!.replace(
      process.env.REGION + ':',
      ''
    );
    if (!adminId) {
      const err = new Error(`invalid adminId `);
      statusCode = 400;
      throw err;
    }
    const result = await createStudent(event, adminId, body);
    console.log("main -> result", result);
    if (result.body) return success(JSON.parse(result.body)); // Return the retrieved item
    else return failure({ status: false, error: 'Item not found.' }); // Return with error
  } catch (err) {
    console.log('main -> err', err);
    return error(statusCode, JSON.parse(event.body!));
  }
}
